name: Kaylani Coffee
favicon: null
layout_spectrum: 1
typography_spectrum: 0.812144641764462
title: Kaylani Coffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0269ba'
    - '#31262b'
    - '#8f4526'
    - '#e8ab49'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
