name: kaylanicoffee
favicon: null
layout_spectrum: 0.37802697834558785
typography_spectrum: 0.812144641764462
title: kaylanicoffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0269ba'
    - '#31262b'
    - '#8f4526'
    - '#e8ab49'
  brandStrength: 0.9375
  lightness: 0.2075881976634264
  saturation: 0.918672077357769
  rhythmicContrast: 0.6889964996371418
purpose: []
